[package]
name = "aplib-extractor"
version = "0.1.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]

[dependencies]
chrono = "0.4.0"
docopt = "1.0.0"
exempi = { version = "2.5.0", git = "https://github.com/hfiguiere/exempi-rs.git" }
lazy_static = "0.2.9"
maplit = "1.0.0"
pbr = "1.0.0"
plist = "0.2.3"
serde = "1.0.15"
serde_derive = "1.0"  # if you're using `derive(Deserialize)`
try_opt = "0.1.1"

[lib]
name = "aplib"

[[bin]]
name = "dumper"
