[package]
name = "aplib-extractor"
version = "0.1.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]

[dependencies]
chrono = "0.4.0"
exempi = { version = "2.5.0" }
lazy_static = "1.4.0"
maplit = "1.0.0"
plist = "0.5.1"
try_opt = "0.1.1"

docopt = { version = "1.0.0", optional = true }
pbr = { version = "1.0.0", optional = true }
serde = { version = "1.0.15", optional = true }
serde_derive = { version = "1.0", optional = true }  # if you're using `derive(Deserialize)`

[lib]
name = "aplib"

[[bin]]
name = "dumper"
required-features = ["binaries"]

[features]
binaries = ["docopt", "pbr", "serde", "serde_derive" ]