[package]
name = "aperture-import"
version = "0.1.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]

[dependencies]
plist = "0.0.12"
docopt = "0.6"
rustc-serialize = "0.3"  # if you're using `derive(RustcDecodable)`
pbr = { git="https://github.com/a8m/pb.git", rev="b403d6b" }

[lib]
name = "aplib"

[[bin]]
name = "dumper"
