[package]
name = "aplib-extractor"
version = "0.1.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]

[dependencies]
plist = "0.2.3"
docopt = "0.8.1"
serde = "1.0.15"
serde_derive = "1.0"  # if you're using `derive(Deserialize)`
try_opt = "0.1.1"
pbr = "1.0.0"
chrono = "0.4.0"

[lib]
name = "aplib"

[[bin]]
name = "dumper"
